### ISSUE TITLE
displaCy Named Entity Visualizer

### ISSUE THREAD

**Issue by soychabela** [MOOC-UNAM-Publico/lecturas_web#2]
[displaCy Named Entity Visualizer](https://explosion.ai/demos/displacy-ent) es una herramienta que permite reconocimiento de entidades nombradas (personas, organizaciones, localidades), capaz de analizar varios idiomas.

**Comment by jairomelo** [comment]
Agregado al mapa

**Comment by jairomelo** [comment]
Herramienta agregada.
